Pandas

In [ ]:
# ! pip install pandas

Requirement already satisfied: pandas in c:\users\it\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\it\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\it\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\it\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\it\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\it\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [4]:
import numpy as np
import pandas as pd

In [ ]:
list1=[2,3,4,1,5]
s1=pd.Series(list1, index=['a','b','c','d','e'])
print(s1)
print(type(s1))
print(s1.dtype)
print(s1.values)
print(s1.index)

a    2
b    3
c    4
d    1
e    5
dtype: int64
<class 'pandas.core.series.Series'>
int64
[2 3 4 1 5]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

Series

In [ ]:
s2=pd.Series(list1)
print(s2)
print(s2.index)

0    2
1    3
2    4
3    1
4    5
dtype: int64
RangeIndex(start=0, stop=5, step=1)

In [17]:
sdata={"kim":85,"lee":75,"choi":65}
s3=pd.Series(sdata)
s3

kim     85
lee     75
choi    65
dtype: int64

DataFrame

2차원 배열 데이터 형식

pd.DataFrame(data, columns=[], index=[])

In [19]:
data={
    "name":['민준','현우','서연','동현','지현'],        # 하나가 필드
    "year":[2023,2024,2022,2025,2024],                # 하나가 필드
    "point":[1.5,1.7,3.6,2.4,2.9]                     # 하나가 필드
    }
df=pd.DataFrame(data)
df

  name  year  point
0   민준  2023    1.5
1   현우  2024    1.7
2   서연  2022    3.6
3   동현  2025    2.4
4   지현  2024    2.9

In [ ]:
names=['민준','현우','서연','동현','지현']
years=[2023,2024,2022,2025,2024]
points=[1.5,1.7,3.6,2.4,2.9]

data=[names, years, points]
print(data)
df1=pd.DataFrame(data).T            # .T 데이터를 가져왔는데 행과 열을 바꾸고 싶을때 .T
df1.columns=['names','years','points'];df1      # python 명령어를 두개 적을때 ; 새미콜론 기입한다.

[['민준', '현우', '서연', '동현', '지현'], [2023, 2024, 2022, 2025, 2024], [1.5, 1.7, 3.6, 2.4, 2.9]]

  names years points
0    민준  2023    1.5
1    현우  2024    1.7
2    서연  2022    3.6
3    동현  2025    2.4
4    지현  2024    2.9

In [30]:
arr=np.array(data).T
arr
df2=pd.DataFrame(arr,columns=["names","years","points"],        # columns 가로 바
                 index=['one','two','theree','four','five'])    # index 세로 바
df2

       names years points
one       민준  2023    1.5
two       현우  2024    1.7
theree    서연  2022    3.6
four      동현  2025    2.4
five      지현  2024    2.9

In [ ]:
print(df2)
print(df2.index)
print(df2.columns)
print(df2.values)

       names years points
one       민준  2023    1.5
two       현우  2024    1.7
theree    서연  2022    3.6
four      동현  2025    2.4
five      지현  2024    2.9
Index(['one', 'two', 'theree', 'four', 'five'], dtype='object')
Index(['names', 'years', 'points'], dtype='object')
[['민준' '2023' '1.5']
 ['현우' '2024' '1.7']
 ['서연' '2022' '3.6']
 ['동현' '2025' '2.4']
 ['지현' '2024' '2.9']]

In [34]:
names=df2['names']
years=df2['years']
points=df2['points']
print(names)
print(type(years))
print(points)

one       민준
two       현우
theree    서연
four      동현
five      지현
Name: names, dtype: object
<class 'pandas.core.series.Series'>
one       1.5
two       1.7
theree    3.6
four      2.4
five      2.9
Name: points, dtype: object

칼럼과 인텍스의 숫자를 알려준다.

In [38]:
print(df2.shape)

(5, 3)

전반적인 데이터 상세설명을 알려준다.

In [39]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, one to five
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   5 non-null      object
 1   years   5 non-null      object
 2   points  5 non-null      object
dtypes: object(3)
memory usage: 160.0+ bytes

In [45]:
chocolate_df=pd.read_csv("data/chocolate_rating.csv",header=None)
chocolate_df.columns=['id','year','kakao','avg']
chocolate_df.to_csv("data/chocol.csv", index=False)

In [47]:
character_df=pd.read_excel("data/characters.xlsx")
print(character_df)
character_df.to_excel("data/char.xlsx",index=False)

   ID   이름  상징색    취미    특징
0   1  뽀로로  파랑색    낚시    펭귄
1   2   에디  주황색  과학실험  사막여우
2   3   크롱  초록색   눈싸움    공룡
3   4   루피  분홍색    요리    비버
4   5   패티  보라색    운동    펭귄