# Pandas

In [17]:
# ! pip install pandas

In [18]:
import numpy as np
import pandas as pd

In [19]:
list1=[2,3,4,1,5]
s1=pd.Series(list1, index=['a','b','c','d','e'])
print(s1)
print(type(s1))
print(s1.dtype)
print(s1.values)
print(s1.index)

a    2
b    3
c    4
d    1
e    5
dtype: int64
<class 'pandas.core.series.Series'>
int64
[2 3 4 1 5]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

Series

In [20]:
s2=pd.Series(list1)
print(s2)
print(s2.index)

0    2
1    3
2    4
3    1
4    5
dtype: int64
RangeIndex(start=0, stop=5, step=1)

In [21]:
sdata={"kim":85,"lee":75,"choi":65}
s3=pd.Series(sdata)
s3

kim     85
lee     75
choi    65
dtype: int64

DataFrame

2차원 배열 데이터 형식

pd.DataFrame(data, columns=[], index=[])

In [22]:
data={
    "name":['민준','현우','서연','동현','지현'],        # 하나가 필드
    "year":[2023,2024,2022,2025,2024],                # 하나가 필드
    "point":[1.5,1.7,3.6,2.4,2.9]                     # 하나가 필드
    }
df=pd.DataFrame(data)
df

  name  year  point
0   민준  2023    1.5
1   현우  2024    1.7
2   서연  2022    3.6
3   동현  2025    2.4
4   지현  2024    2.9

In [23]:
names=['민준','현우','서연','동현','지현']
years=[2023,2024,2022,2025,2024]
points=[1.5,1.7,3.6,2.4,2.9]

data=[names, years, points]
print(data)
df1=pd.DataFrame(data).T            # .T 데이터를 가져왔는데 행과 열을 바꾸고 싶을때 .T
df1.columns=['names','years','points'];df1      # python 명령어를 두개 적을때 ; 새미콜론 기입한다.

[['민준', '현우', '서연', '동현', '지현'], [2023, 2024, 2022, 2025, 2024], [1.5, 1.7, 3.6, 2.4, 2.9]]

  names years points
0    민준  2023    1.5
1    현우  2024    1.7
2    서연  2022    3.6
3    동현  2025    2.4
4    지현  2024    2.9

In [24]:
arr=np.array(data).T
arr
df2=pd.DataFrame(arr,columns=["names","years","points"],        # columns 가로 바
                 index=['one','two','theree','four','five'])    # index 세로 바
df2

       names years points
one       민준  2023    1.5
two       현우  2024    1.7
theree    서연  2022    3.6
four      동현  2025    2.4
five      지현  2024    2.9

In [25]:
print(df2)
print(df2.index)
print(df2.columns)
print(df2.values)

       names years points
one       민준  2023    1.5
two       현우  2024    1.7
theree    서연  2022    3.6
four      동현  2025    2.4
five      지현  2024    2.9
Index(['one', 'two', 'theree', 'four', 'five'], dtype='object')
Index(['names', 'years', 'points'], dtype='object')
[['민준' '2023' '1.5']
 ['현우' '2024' '1.7']
 ['서연' '2022' '3.6']
 ['동현' '2025' '2.4']
 ['지현' '2024' '2.9']]

In [26]:
names=df2['names']
years=df2['years']
points=df2['points']
print(names)
print(type(years))
print(points)

one       민준
two       현우
theree    서연
four      동현
five      지현
Name: names, dtype: object
<class 'pandas.core.series.Series'>
one       1.5
two       1.7
theree    3.6
four      2.4
five      2.9
Name: points, dtype: object

칼럼과 인텍스의 숫자를 알려준다.

In [27]:
print(df2.shape)

(5, 3)

전반적인 데이터 상세설명을 알려준다.

In [28]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, one to five
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   5 non-null      object
 1   years   5 non-null      object
 2   points  5 non-null      object
dtypes: object(3)
memory usage: 160.0+ bytes

In [29]:
chocolate_df=pd.read_csv("data/chocolate_rating.csv",header=None)
chocolate_df.columns=['id','year','kakao','avg']
chocolate_df.to_csv("data/chocol.csv", index=False)

In [30]:
character_df=pd.read_excel("data/characters.xlsx")
print(character_df)
character_df.to_excel("data/char.xlsx",index=False)

   ID   이름  상징색    취미    특징
0   1  뽀로로  파랑색    낚시    펭귄
1   2   에디  주황색  과학실험  사막여우
2   3   크롱  초록색   눈싸움    공룡
3   4   루피  분홍색    요리    비버
4   5   패티  보라색    운동    펭귄

파일 -> 데이터 프레임으로 읽어오기

In [ ]:
chocolate_df=pd.read_csv('./chocolate_rating.csv')

FileNotFoundError: [Errno 2] No such file or directory: './chocolate_rating.csv'

DataFrame : 조회

In [33]:
df2

       names years points
one       민준  2023    1.5
two       현우  2024    1.7
theree    서연  2022    3.6
four      동현  2025    2.4
five      지현  2024    2.9

In [34]:
chocolate_df

        id  year  kakao   avg
0        1  2016   0.63  3.75
1        2  2015   0.70  2.75
2        3  2015   0.70  3.00
3        4  2015   0.70  3.50
4        5  2015   0.70  3.50
...    ...   ...    ...   ...
1790  1791  2011   0.70  3.75
1791  1792  2011   0.65  3.00
1792  1793  2011   0.65  3.50
1793  1794  2011   0.62  3.25
1794  1795  2010   0.65  3.00

[1795 rows x 4 columns]

In [35]:
character_df

   ID   이름  상징색    취미    특징
0   1  뽀로로  파랑색    낚시    펭귄
1   2   에디  주황색  과학실험  사막여우
2   3   크롱  초록색   눈싸움    공룡
3   4   루피  분홍색    요리    비버
4   5   패티  보라색    운동    펭귄

In [37]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, one to five
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   5 non-null      object
 1   years   5 non-null      object
 2   points  5 non-null      object
dtypes: object(3)
memory usage: 160.0+ bytes

In [38]:
chocolate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1795 non-null   int64
 1   year    1795 non-null   int64
 2   kakao   1795 non-null   float64
 3   avg     1795 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 56.2 KB

In [39]:
character_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      5 non-null      int64
 1   이름      5 non-null      object
 2   상징색     5 non-null      object
 3   취미      5 non-null      object
 4   특징      5 non-null      object
dtypes: int64(1), object(4)
memory usage: 332.0+ bytes

컴럼이름 바꿈

In [ ]:
chocolate_df.columns=['번호','연도','함유량','평점']
chocolate_df            # 전체 다 보여줌

        번호    연도   함유량    평점
0        1  2016  0.63  3.75
1        2  2015  0.70  2.75
2        3  2015  0.70  3.00
3        4  2015  0.70  3.50
4        5  2015  0.70  3.50
...    ...   ...   ...   ...
1790  1791  2011  0.70  3.75
1791  1792  2011  0.65  3.00
1792  1793  2011  0.65  3.50
1793  1794  2011  0.62  3.25
1794  1795  2010  0.65  3.00

[1795 rows x 4 columns]

In [44]:
chocolate_df.head()     # 앞에 5개만 보여줌

   번호    연도   함유량    평점
0   1  2016  0.63  3.75
1   2  2015  0.70  2.75
2   3  2015  0.70  3.00
3   4  2015  0.70  3.50
4   5  2015  0.70  3.50

In [45]:
chocolate_df.tail()     # 맨 마지막 것 5개만 보여줌

        번호    연도   함유량    평점
1790  1791  2011  0.70  3.75
1791  1792  2011  0.65  3.00
1792  1793  2011  0.65  3.50
1793  1794  2011  0.62  3.25
1794  1795  2010  0.65  3.00

In [48]:
chocolate_df[:10]       # 행 0 부터 10개 보여줌 (list 슬라이싱하는 방법)

   번호    연도   함유량    평점
0   1  2016  0.63  3.75
1   2  2015  0.70  2.75
2   3  2015  0.70  3.00
3   4  2015  0.70  3.50
4   5  2015  0.70  3.50
5   6  2014  0.70  2.75
6   7  2014  0.70  3.50
7   8  2014  0.70  3.50
8   9  2014  0.70  3.75
9  10  2014  0.70  4.00

In [50]:
chocolate_df[10:20]       # 행 10 부터 20개 보여줌 (list 슬라이싱하는 방법)

    번호    연도  함유량    평점
10  11  2013  0.7  2.75
11  12  2013  0.7  3.00
12  13  2013  0.7  3.25
13  14  2013  0.7  3.75
14  15  2013  0.7  2.75
15  16  2013  0.7  3.00
16  17  2013  0.7  3.25
17  18  2013  0.7  4.00
18  19  2013  0.7  3.25
19  20  2013  0.7  3.50

In [52]:
chocolate_df.describe()

                번호           연도          함유량           평점
count  1795.000000  1795.000000  1795.000000  1795.000000
mean    898.000000  2012.325348     0.717003     3.185933
std     518.316184     2.927210     0.063230     0.478062
min       1.000000  2006.000000     0.420000     1.000000
25%     449.500000  2010.000000     0.700000     2.875000
50%     898.000000  2013.000000     0.700000     3.250000
75%    1346.500000  2015.000000     0.750000     3.500000
max    1795.000000  2017.000000     1.000000     5.000000

In [56]:
df2.describe()
# df2.info()

       names years points
count      5     5      5
unique     5     4      5
top       민준  2024    1.5
freq       1     2      1

In [54]:
character_df.describe()

             ID
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

In [58]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, one to five
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   5 non-null      object
 1   years   5 non-null      object
 2   points  5 non-null      object
dtypes: object(3)
memory usage: 160.0+ bytes

years 타입을 정수로(int)

In [59]:
df2['years']=df2['years'].astype(np.int64)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, one to five
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   5 non-null      object
 1   years   5 non-null      int64
 2   points  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 332.0+ bytes

point 타입을 실수로(float)

In [62]:
df2['points']=df2['points'].astype(np.float64)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, one to five
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   5 non-null      object
 1   years   5 non-null      int64
 2   points  5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 332.0+ bytes

In [63]:
df2.describe()

             years    points
count     5.000000  5.000000
mean   2023.600000  2.420000
std       1.140175  0.864292
min    2022.000000  1.500000
25%    2023.000000  1.700000
50%    2024.000000  2.400000
75%    2024.000000  2.900000
max    2025.000000  3.600000

Pandas

정렬 

인덱스 기준 정렬

ascending : True(오름차순), False(내림차순)

In [66]:
df2.sort_index(axis=0, ascending=False)

       names  years  points
two       현우   2024     1.7
theree    서연   2022     3.6
one       민준   2023     1.5
four      동현   2025     2.4
five      지현   2024     2.9

In [72]:
df2.sort_values(by=['years','points'], ascending=False)

       names  years  points
four      동현   2025     2.4
five      지현   2024     2.9
two       현우   2024     1.7
one       민준   2023     1.5
theree    서연   2022     3.6

Pandas 데이터 조회

1개 일때는 요렇게 한다.

In [79]:
df2['names']    # 데이터 프레임
df2.names       # 시리즈

one       민준
two       현우
theree    서연
four      동현
five      지현
Name: names, dtype: object

두개 이상일때는 리스트 형식으로 만들어야 한다.

In [75]:
df2[['names','points']]

       names  points
one       민준     1.5
two       현우     1.7
theree    서연     3.6
four      동현     2.4
five      지현     2.9

하나만 가져올때

In [91]:
df2.iloc[::2,0:2]

       names  years
one       민준   2023
theree    서연   2022
five      지현   2024

In [86]:
df2

       names  years  points
one       민준   2023     1.5
two       현우   2024     1.7
theree    서연   2022     3.6
four      동현   2025     2.4
five      지현   2024     2.9

In [92]:
print(df2.iloc[0:3, 0:2])

       names  years
one       민준   2023
two       현우   2024
theree    서연   2022

In [94]:
print(df2.iloc[[0,3],[0,2]])

     names  points
one     민준     1.5
four    동현     2.4

In [100]:
print(df2.iloc[::2, :2])

       names  years
one       민준   2023
theree    서연   2022
five      지현   2024

In [108]:
df2.loc['one']
df2.loc['one':'theree']
df2.loc[['one','theree']]
df2.loc['one':'four',['names','points']]

       names  points
one       민준     1.5
two       현우     1.7
theree    서연     3.6
four      동현     2.4

df2.loc[행조건, 열조건]

In [112]:
print(df2.loc[df2['years']==2024])
print(df2.loc[df2['points']>=2.0])

     names  years  points
two     현우   2024     1.7
five    지현   2024     2.9
       names  years  points
theree    서연   2022     3.6
four      동현   2025     2.4
five      지현   2024     2.9

In [123]:
print(chocolate_df)
chocolate_df.loc[chocolate_df['평점']>=4]
chocolate_df.loc[chocolate_df['함유량']<=7,['번호','평점']]

        번호    연도   함유량    평점
0        1  2016  0.63  3.75
1        2  2015  0.70  2.75
2        3  2015  0.70  3.00
3        4  2015  0.70  3.50
4        5  2015  0.70  3.50
...    ...   ...   ...   ...
1790  1791  2011  0.70  3.75
1791  1792  2011  0.65  3.00
1792  1793  2011  0.65  3.50
1793  1794  2011  0.62  3.25
1794  1795  2010  0.65  3.00

[1795 rows x 4 columns]

        번호    평점
0        1  3.75
1        2  2.75
2        3  3.00
3        4  3.50
4        5  3.50
...    ...   ...
1790  1791  3.75
1791  1792  3.00
1792  1793  3.50
1793  1794  3.25
1794  1795  3.00

[1795 rows x 2 columns]

In [126]:
print(df2[df2['names'].isin(['민준','현우'])])
print(df2[df2.names.isin(['민준','현우'])])

    names  years  points
one    민준   2023     1.5
two    현우   2024     1.7
    names  years  points
one    민준   2023     1.5
two    현우   2024     1.7

In [136]:
print(df2[df2.points>2])                            # points가 2보다 큰 것
print(df2[(df2.years==2024) & (df2.points>2)])      # years가 2024이고, points가 2보다 큰 것
print(df2[(df2.years==2025) | (df2.points>2)])      # years가 2025이거나, points가 2보다 큰 것
print(df2[df2.names.str.contains('현')])            # names중에 '현'이 포함된 것

       names  years  points
theree    서연   2022     3.6
four      동현   2025     2.4
five      지현   2024     2.9
     names  years  points
five    지현   2024     2.9
       names  years  points
theree    서연   2022     3.6
four      동현   2025     2.4
five      지현   2024     2.9
     names  years  points
two     현우   2024     1.7
four    동현   2025     2.4
five    지현   2024     2.9

Pandas 데이터프레임 수정

In [139]:
df2['points2']=df2.points+0.5;df2       # 새 필드를 추가할때는 요런 형태로 해야 한다.

       names  years  points  points2
one       민준   2023     1.5      2.0
two       현우   2024     1.7      2.2
theree    서연   2022     3.6      4.1
four      동현   2025     2.4      2.9
five      지현   2024     2.9      3.4

In [147]:
df2.points2=df2.points*0.5;df2          # 위와 검색할때만 같다.(이미 있는 데이터는 수정가능하다)

       names  years  points  points2
one       민준   2023     1.5     0.75
two       현우   2024     1.7     0.85
theree    서연   2022     3.6     1.80
four      동현   2025     2.4     1.20
five      지현   2024     2.9     1.45

하나의 행일때

In [150]:
df2.loc['one','points2']=df2.loc['one','points']+1;df2

       names  years  points  points2
one       민준   2023     1.5     2.50
two       현우   2024     1.7     0.85
theree    서연   2022     3.6     1.80
four      동현   2025     2.4     1.20
five      지현   2024     2.9     1.45

여러 행일때

In [158]:
df2.loc['two':'theree','points2']=1*2;df2      # 1*2 = 2인 것을 넣는다.

       names  years  points  points2
one       민준   2023     1.5     2.50
two       현우   2024     1.7     2.00
theree    서연   2022     3.6     2.00
four      동현   2025     2.4     1.20
five      지현   2024     2.9     1.45

In [ ]:
df2.loc['two':'theree','points2']=[1]*2;df2     # [1]*2 = 같은 수를 2번 반복한다.

       names  years  points  points2
one       민준   2023     1.5     2.50
two       현우   2024     1.7     1.00
theree    서연   2022     3.6     1.00
four      동현   2025     2.4     1.20
five      지현   2024     2.9     1.45

In [ ]:
df2['aaa']=[1]*5;df2
df2['aaa']=[1,1,1,1,1];df2   # 위에 것과 똑같은 말이다.

       names  years  points  points2  aaa
one       민준   2023     1.5     2.50    1
two       현우   2024     1.7     2.00    1
theree    서연   2022     3.6     2.00    1
four      동현   2025     2.4     1.20    1
five      지현   2024     2.9     1.45    1

In [169]:
df2['bbb']=[2,3,4,5,6];df2      # 리스트를 넣을때는 갯수를 정확하게 맞추어서 넣어야 한다.

       names  years  points  points2  aaa  bbb
one       민준   2023     1.5     2.50    1    2
two       현우   2024     1.7     2.00    1    3
theree    서연   2022     3.6     2.00    1    4
four      동현   2025     2.4     1.20    1    5
five      지현   2024     2.9     1.45    1    6

In [174]:
df11=df1.set_index('names');df11

      years points
names
민준     2023    1.5
현우     2024    1.7
서연     2022    3.6
동현     2025    2.4
지현     2024    2.9

In [178]:
df1.set_index('names',inplace=True);df1

      years points
names
민준     2023    1.5
현우     2024    1.7
서연     2022    3.6
동현     2025    2.4
지현     2024    2.9

In [189]:
df1.reset_index(inplace=True);df1
df1.set_index('points', inplace=True);df1
df1.reset_index(inplace=True);df1

ValueError: cannot insert level_0, already exists

In [199]:
df1=df1.drop('index', axis=1);df1

KeyError: "['index'] not found in axis"

삭제 잘하지 않는다. 검색해서 새로 만든다.

데이터 치환

In [201]:
df['gender']=['남자','남자','여자','남자','여자'];df

  name  year  point gender
0   민준  2023    1.5     남자
1   현우  2024    1.7     남자
2   서연  2022    3.6     여자
3   동현  2025    2.4     남자
4   지현  2024    2.9     여자

In [202]:
reo_cond={'gender':{'남자':1, '여자':2}}
df=df.replace(reo_cond);df

C:\Users\it\AppData\Local\Temp\ipykernel_19100\3268663206.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace(reo_cond);df

  name  year  point  gender
0   민준  2023    1.5       1
1   현우  2024    1.7       1
2   서연  2022    3.6       2
3   동현  2025    2.4       1
4   지현  2024    2.9       2

데이터프레임 연산

In [204]:
name=['kim','lee','choi','park','jung']
year=[1,2,1,2,1]
kor=[85,95,75,70,80]
eng=[85,90,75,71,80]
math=[85,91,72,75,80]
data=[name,year,kor,eng,math]
arr=np.array(data).T
data_df=pd.DataFrame(arr,columns=['name','year','kor','eng','math'])
data_df

   name year kor eng math
0   kim    1  85  85   85
1   lee    2  95  90   91
2  choi    1  75  75   72
3  park    2  70  71   75
4  jung    1  80  80   80

In [208]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   year    5 non-null      object
 2   kor     5 non-null      object
 3   eng     5 non-null      object
 4   math    5 non-null      object
 5   total   5 non-null      object
dtypes: object(6)
memory usage: 372.0+ bytes

In [211]:
data_df['kor']=data_df['kor'].astype('Int64')
data_df['eng']=data_df['eng'].astype('Int64')
data_df['math']=data_df['math'].astype('Int64')
data_df['year']=data_df['year'].astype('Int64')
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   year    5 non-null      Int64
 2   kor     5 non-null      Int64
 3   eng     5 non-null      Int64
 4   math    5 non-null      Int64
 5   total   5 non-null      object
dtypes: Int64(4), object(2)
memory usage: 392.0+ bytes

In [212]:
data_df['total']=data_df.kor+data_df.eng+data_df.math;data_df

   name  year  kor  eng  math  total
0   kim     1   85   85    85    255
1   lee     2   95   90    91    276
2  choi     1   75   75    72    222
3  park     2   70   71    75    216
4  jung     1   80   80    80    240

In [ ]:
data_df['avg']=data_df.total/3;data_df

In [213]:
data_df.describe()

           year       kor       eng      math     total
count       5.0       5.0       5.0       5.0       5.0
mean        1.4      81.0      80.2      80.6     241.8
std    0.547723  9.617692  7.596052  7.635444  24.51938
min         1.0      70.0      71.0      72.0     216.0
25%         1.0      75.0      75.0      75.0     222.0
50%         1.0      80.0      80.0      80.0     240.0
75%         2.0      85.0      85.0      85.0     255.0
max         2.0      95.0      90.0      91.0     276.0

In [215]:
data_df.year.value_counts()     # 숫자가 아니라도 카운터를 세어준다.

year
1    3
2    2
Name: count, dtype: Int64

카카오 평점 확인 해봅시다.

In [216]:
chocolate_df['평점'].value_counts()

평점
3.50    392
3.00    341
3.25    303
2.75    259
3.75    210
2.50    127
4.00     98
2.00     32
2.25     14
1.50     10
1.00      4
1.75      3
5.00      2
Name: count, dtype: int64

In [217]:
chocolate_df['함유량'].value_counts()

함유량
0.70    672
0.75    222
0.72    189
0.65     78
0.80     72
0.74     52
0.68     47
0.73     44
0.60     43
0.85     36
0.64     34
0.77     33
0.71     31
0.67     27
0.66     23
0.76     23
1.00     20
0.82     17
0.78     17
0.55     16
0.62     14
0.63     12
0.69     10
0.61      9
0.90      8
0.88      8
0.58      8
0.81      5
0.83      4
0.84      4
0.91      3
0.99      2
0.89      2
0.56      2
0.46      1
0.53      1
0.79      1
0.57      1
0.86      1
0.50      1
0.42      1
0.87      1
Name: count, dtype: int64

In [219]:
data_df.groupby('year')['total'].sum()
# 1학년 학생의 점수들의 합, 2학년 학생의 점수들의 합

year
1    717
2    492
Name: total, dtype: Int64

In [ ]:
data_df.groupby('year')[['kor','eng','kor']].sum()  # 합

      kor  eng  kor
year
1     240  240  240
2     165  161  165

In [222]:
data_df.groupby('year')[['kor','eng','math']].mean()  # 평균

       kor   eng  math
year
1     80.0  80.0  79.0
2     82.5  80.5  83.0

In [230]:
data_df.groupby('year')['total'].agg(['sum','mean','median','count'])
data_df

   name  year  kor  eng  math  total
0   kim     1   85   85    85    255
1   lee     2   95   90    91    276
2  choi     1   75   75    72    222
3  park     2   70   71    75    216
4  jung     1   80   80    80    240

In [234]:
agg1={'kor':'sum','total':'median','eng':'count'}
data_df.groupby('year').agg(agg1)

      kor  total  eng
year
1     240  240.0    3
2     165  246.0    2

In [235]:
df2

       names  years  points  points2  aaa  bbb
one       민준   2023     1.5     2.50    1    2
two       현우   2024     1.7     2.00    1    3
theree    서연   2022     3.6     2.00    1    4
four      동현   2025     2.4     1.20    1    5
five      지현   2024     2.9     1.45    1    6

문제
1. df2를 사용하여 연도별 point의 합과, 평균을 구하라
2. 연도별 points의 중앙값 points2의 갯수를 구하라.

1. df2를 사용하여 연도별 point의 합과, 평균을 구하라

In [242]:
df2.groupby('years')['points'].agg(['sum','mean'])

       sum  mean
years
2022   3.6   3.6
2023   1.5   1.5
2024   4.6   2.3
2025   2.4   2.4

2. 연도별 points의 중앙값 points2의 갯수를 구하라.

In [252]:
# it's me.
group2={'points':'median','points2':'count'}
df2.groupby('years').agg(group2)

# 풀이
df2.groupby('years')[['points','points2']].sum()

       points  points2
years
2022      3.6     2.00
2023      1.5     2.50
2024      4.6     3.45
2025      2.4     1.20

In [260]:
# 풀이2
df2.groupby('years').agg({'points':'median','points2':'count'})
df2

       names  years  points  points2  aaa  bbb
one       민준   2023     1.5     2.50    1    2
two       현우   2024     1.7     2.00    1    3
theree    서연   2022     3.6     2.00    1    4
four      동현   2025     2.4     1.20    1    5
five      지현   2024     2.9     1.45    1    6

Pandas  데이터프레임 조인

In [264]:
df20=df2[['names','years','points']]
df21=df2[['names','points2']]

In [265]:
df20.set_index('names',inplace=True)

In [267]:
df20

       years  points
names
민준      2023     1.5
현우      2024     1.7
서연      2022     3.6
동현      2025     2.4
지현      2024     2.9

In [266]:
df21.set_index('names',inplace=True);df21

       points2
names
민준        2.50
현우        2.00
서연        2.00
동현        1.20
지현        1.45

가로로 합치기 

왼쪽 테이블의 인덱스와 오른쪽 테이블의 인텍스를 join 하겠다.

In [270]:
join_df1=df20.merge(df21,left_index=True, right_index=True);join_df1

       years  points  points2
names
민준      2023     1.5     2.50
현우      2024     1.7     2.00
서연      2022     3.6     2.00
동현      2025     2.4     1.20
지현      2024     2.9     1.45

세로로 합치기

In [273]:
con_df1=df2[:3]
con_df2=df2[3:]
con_df2

     names  years  points  points2  aaa  bbb
four    동현   2025     2.4     1.20    1    5
five    지현   2024     2.9     1.45    1    6

concat 컬럼의 수가 같아야 한다.

In [275]:
con=pd.concat([con_df1, con_df2], axis=0);con

       names  years  points  points2  aaa  bbb
one       민준   2023     1.5     2.50    1    2
two       현우   2024     1.7     2.00    1    3
theree    서연   2022     3.6     2.00    1    4
four      동현   2025     2.4     1.20    1    5
five      지현   2024     2.9     1.45    1    6

In [282]:
print(df20)
print(df21)
con2=pd.concat([df20,df21],axis=1);con2

       years  points
names
민준      2023     1.5
현우      2024     1.7
서연      2022     3.6
동현      2025     2.4
지현      2024     2.9
       points2
names
민준        2.50
현우        2.00
서연        2.00
동현        1.20
지현        1.45

       years  points  points2
names
민준      2023     1.5     2.50
현우      2024     1.7     2.00
서연      2022     3.6     2.00
동현      2025     2.4     1.20
지현      2024     2.9     1.45

In [287]:
con2=pd.concat([df,df1],axis=1);con2

  name  year  point  gender  points  level_0 names
0   민준  2023    1.5       1     1.5        0    민준
1   현우  2024    1.7       1     1.7        1    현우
2   서연  2022    3.6       2     3.6        2    서연
3   동현  2025    2.4       1     2.4        3    동현
4   지현  2024    2.9       2     2.9        4    지현