실습 문제

In [2]:
import numpy as np
import pandas as pd

In [14]:
name=['허준호','이가원','배규민','고고림','이새봄','이보람','이루리','오다현']
gender=['남자','여자','남자','남자','여자','여자','여자','여자']
age=[30,24,23,21,28,26,24,24]
hight=[183,162,179,182,160,163,157,172]
data={'이름':name, '성별':gender,'나이':age,'키':hight}
df=pd.DataFrame(data);df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [17]:
# 1.
df['몸무게']=[ 82.5,  50.0,  78.0 ,  80.5,  48.0,   51.2,  46.0,  65.0]

df

    이름  성별  나이    키   몸무게
0  허준호  남자  30  183  82.5
1  이가원  여자  24  162  50.0
2  배규민  남자  23  179  78.0
3  고고림  남자  21  182  80.5
4  이새봄  여자  28  160  48.0
5  이보람  여자  26  163  51.2
6  이루리  여자  24  157  46.0
7  오다현  여자  24  172  65.0

In [32]:
#2.
df[df.키>180]

    이름  성별  나이    키   몸무게
0  허준호  남자  30  183  82.5
3  고고림  남자  21  182  80.5

In [39]:
#3.여자중키가160보다큰사람을조회하라.
df[df.키>160 & df.성별==여자]

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [ ]:
#4.성별키의평균을구하라
df.groupby('성별')['키'].agg('mean')

1. 몸무게column  추가: [ 82.5,  50.0,  78.0 ,  80.5,  48.0,   51.2,  46.0,  65.0]
 ② 키가180 이상은사람의이름과키를조회하라.
 ③ 여자중키가160보다큰사람을조회하라.
 ④ 성별키의평균을구하라
⑤ 성별키와몸무게의평균.합, 인원수를구하라.
 ⑥ 이름과성별칼럼을추출하여df2를생성한다.
 ⑦ df2에[연락처] 칼럼을추가한다.(데이터: [‘010-1111-2525’,….. 8개 ]
 ⑧ df와df2의이름칼럼을인덱스로설정한다.
 ⑨ df와df2를인덱스를기준으로조인(joindf)한다.
 ⑩ 데이터프레임을csv파일(test_df.csv)로 저장한다.
 ⑪ 저장된test_df.csv) 파일을 데이터프레임으로로드한다